[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Form handling
[[forms]]
  name = "contact"

# Redirect all traffic to HTTPS
[[redirects]]
  from = "http://kuteyilegalgroup.com/*"
  to = "https://kuteyilegalgroup.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.kuteyilegalgroup.com/*"
  to = "https://www.kuteyilegalgroup.com/:splat"
  status = 301
  force = true

# Redirect www to non-www (optional - choose one approach)
[[redirects]]
  from = "https://www.kuteyilegalgroup.com/*"
  to = "https://kuteyilegalgroup.com/:splat"
  status = 301
  force = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
